version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_s3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: 1
    volumes:
      - "/tmp/localstack:/var/lib/localstack"