version: '3.9'

volumes: 
  grafana_data: {}  # store Grafana data persistently
  prefect_data: {}  # store Prefect data persistently

networks:
  front-tier:  # to access via web browser
  back-tier:  # for internal communication between services

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:  # manage databases via a web interface
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier  

  grafana:
    image: grafana/grafana-enterprise
    user: "472"
    ports:
      - "3001:3000"
    volumes:
      - ./config/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ./config/dashboards_config/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./dashboards:/opt/grafana/dashboards
    networks:
      - back-tier
      - front-tier
    restart: always

  prefect-server:
    image: prefecthq/prefect:3-latest
    restart: always
    volumes:
      - prefect_data:/root/.prefect
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/ui
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:////root/.prefect/prefect.db
    ports:
      - "4200:4200"
    networks:
      - back-tier
      - front-tier
    command: prefect server start --host 0.0.0.0