{
 "title": "Evidently dashboard",
 "time": { "from": "2022-01-26T10:05:11.008Z", "to": "2022-03-02T07:28:22.776Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp as time,\r\n  prediction_drift\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp as time,\r\n  share_missing_values\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp as time,\r\n  num_drifted_columns\r\nFROM evidently_metrics\r\nWHERE $__timeFilter(timestamp)\r\nORDER BY timestamp"
    }
   ]
  }
 ]
}